# Generated by Django 5.0.4 on 2025-09-22 17:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('reference_code', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_applied', models.BooleanField(blank=True, default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ecommerce_goods_receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'New'), (1, 'Confirmed'), (2, 'Packing'), (3, 'Shipped'), (4, 'Completed'), (5, 'Cancelled')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='account_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ecommerce.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Bank transfer'), (1, 'Cash on delivery')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Booked'), (1, 'Packing'), (2, 'Delivering'), (3, 'Delivered'), (4, 'Return requested'), (5, 'Returning'), (6, 'Returned')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField(blank=True, default=0.0)),
                ('unit_cost', models.FloatField(blank=True, default=0.0)),
                ('amount', models.FloatField(blank=True, default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_items', to='ecommerce.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.goodsreceipt')),
            ],
            options={
                'db_table': 'ecommerce_goods_receipt_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
