# Generated by Django 5.2.6 on 2025-09-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0004_alter_goodsreceiptitem_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
