# Generated by Django 5.0.4 on 2025-09-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_promotion_discount_promotion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='district_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='province_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ward_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
