# Generated by Django 5.0.4 on 2025-09-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_customer_district_id_customer_province_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
