# Generated by Django 5.0.4 on 2025-10-26 07:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_customer_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_quantity', models.FloatField(default=0.0, help_text='Current stock quantity')),
                ('min_quantity', models.FloatField(default=0.0, help_text='Minimum stock level')),
                ('max_quantity', models.FloatField(blank=True, help_text='Maximum stock level', null=True)),
                ('reserved_quantity', models.FloatField(default=0.0, help_text='Reserved quantity for orders')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='ecommerce.product')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'db_table': 'ecommerce_inventory',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjust', 'Adjustment'), ('reserve', 'Reserve'), ('unreserve', 'Unreserve')], max_length=20)),
                ('quantity', models.FloatField(help_text='Quantity change (positive for in, negative for out)')),
                ('reference_number', models.CharField(blank=True, help_text='Reference number (order, receipt, etc.)', max_length=100)),
                ('reason', models.TextField(blank=True, help_text='Reason for transaction')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ecommerce.inventory')),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'db_table': 'ecommerce_inventory_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
