# Generated by Django 5.0.4 on 2025-10-28 08:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_inventory_inventorytransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('low_stock_threshold_type', models.CharField(choices=[('min_quantity', 'Use Min Quantity'), ('percentage', 'Percentage of Max'), ('fixed', 'Fixed Value')], default='min_quantity', help_text='How to determine low stock threshold', max_length=20)),
                ('low_stock_threshold_value', models.FloatField(default=0.0, help_text='Value for low stock (e.g., 10 for fixed, 20 for 20%)')),
                ('out_of_stock_threshold', models.FloatField(default=0.0, help_text='Below this value is considered out of stock')),
                ('enable_auto_reorder', models.BooleanField(default=False, help_text='Automatically create purchase orders when stock is low')),
                ('auto_reorder_quantity_type', models.CharField(choices=[('max_quantity', 'Fill to Max Quantity'), ('fixed', 'Fixed Reorder Quantity'), ('multiple', 'Multiple of Min Quantity')], default='max_quantity', help_text='How to calculate reorder quantity', max_length=20)),
                ('auto_reorder_quantity_value', models.FloatField(default=0.0, help_text='Value for auto reorder calculation')),
                ('allow_negative_stock', models.BooleanField(default=False, help_text='Allow inventory to go below zero (backorder)')),
                ('require_transaction_reason', models.BooleanField(default=False, help_text='Require reason for manual stock adjustments')),
                ('require_transaction_reference', models.BooleanField(default=False, help_text='Require reference number for stock adjustments')),
                ('in_stock_label', models.CharField(default='In Stock', help_text='Display label for in-stock items', max_length=50)),
                ('low_stock_label', models.CharField(default='Low Stock', help_text='Display label for low-stock items', max_length=50)),
                ('out_of_stock_label', models.CharField(default='Out of Stock', help_text='Display label for out-of-stock items', max_length=50)),
                ('auto_reserve_on_order', models.BooleanField(default=True, help_text='Automatically reserve stock when order is placed')),
                ('reservation_expiry_hours', models.IntegerField(default=24, help_text='Hours before unreleased reservations expire')),
                ('enable_multi_warehouse', models.BooleanField(default=False, help_text='Enable multi-warehouse inventory tracking')),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration can be active')),
            ],
            options={
                'verbose_name': 'Inventory Configuration',
                'verbose_name_plural': 'Inventory Configurations',
                'db_table': 'ecommerce_inventory_configuration',
                'ordering': ['-created_at'],
            },
        ),
    ]
