# Generated by Django 5.0.4 on 2025-10-30 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
        ('ecommerce', '0010_inventoryconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsreceiptitem',
            options={},
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipt_item_units', to='contents.shortcontent'),
        ),
    ]
