# Generated by Django 5.0.4 on 2025-10-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_goodsreceiptitem_options_goodsreceiptitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceipt',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='reference_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
