# Generated by Django 5.0.4 on 2025-11-10 14:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_remove_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_reference',
            field=models.CharField(blank=True, help_text='Bank transaction reference number', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('momo', 'MoMo'), ('zalopay', 'ZaloPay'), ('cod', 'Cash on Delivery'), ('refund', 'Refund')], default='bank_transfer', help_text='Type of payment transaction', max_length=50)),
                ('transaction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Status of the transaction', max_length=50)),
                ('amount', models.FloatField(default=0.0, help_text='Transaction amount')),
                ('currency', models.CharField(default='VND', help_text='Currency code (e.g., VND, USD)', max_length=10)),
                ('bank_reference', models.CharField(blank=True, help_text='Bank transaction reference number', max_length=255, null=True)),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment gateway (MoMo, ZaloPay, etc.)', max_length=255, null=True)),
                ('gateway_response', models.JSONField(blank=True, help_text='Response data from payment gateway', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the transaction', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the transaction was processed', null=True)),
                ('order', models.ForeignKey(help_text='Order associated with this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='ecommerce.order')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'ecommerce_payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
