# Generated by Django 5.0.4 on 2025-11-10 15:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_remove_product_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, help_text='Review title', max_length=200)),
                ('comment', models.TextField(help_text='Review content', max_length=2000)),
                ('images', models.JSONField(blank=True, default=list, help_text='Review images URLs')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Customer has purchased this product')),
                ('is_approved', models.BooleanField(default=True, help_text='Review is approved by admin')),
                ('helpful_count', models.IntegerField(default=0, help_text='Number of customers who found this helpful')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ecommerce.customer')),
                ('order', models.ForeignKey(blank=True, help_text='Order that contains this product (for verification)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='ecommerce.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ecommerce.product')),
            ],
            options={
                'db_table': 'ecommerce_product_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_helpful', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_reviews', to='ecommerce.customer')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_marks', to='ecommerce.productreview')),
            ],
            options={
                'db_table': 'ecommerce_review_helpful',
            },
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', '-created_at'], name='ecommerce_p_product_4ff65f_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'rating'], name='ecommerce_p_product_0a01c6_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['customer'], name='ecommerce_p_custome_8e2480_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'customer', 'order')},
        ),
        migrations.AddIndex(
            model_name='reviewhelpful',
            index=models.Index(fields=['review', 'customer'], name='ecommerce_r_review__52d3e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpful',
            unique_together={('review', 'customer')},
        ),
    ]
