# Generated by Django 5.0.4 on 2025-11-20 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_order_bank_reference_paymenttransaction'),
        ('ecommerce', '0015_productreview_reviewhelpful_and_more'),
    ]

    operations = [
    ]
