# Generated by Django 5.0.4 on 2025-11-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_merge_20251120_1835'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='order',
        #     name='bank_reference',
        # ),  # Commented out: field does not exist in database
        migrations.AddField(
            model_name='paymenttransaction',
            name='bank_code',
            field=models.CharField(blank=True, help_text='Bank code (for VNPay)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='card_type',
            field=models.CharField(blank=True, help_text='Card type (for VNPay)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Transaction ID from payment gateway (VNPay, MoMo, ZaloPay, etc.)', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('vnpay', 'VNPay'), ('momo', 'MoMo'), ('zalopay', 'ZaloPay'), ('cod', 'Cash on Delivery'), ('refund', 'Refund')], default='bank_transfer', help_text='Type of payment transaction', max_length=50),
        ),
    ]
