# Generated by Django 5.0.4 on 2025-11-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_remove_order_bank_reference_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='order',
        #     name='bank_reference',
        # ),  # Commented out: field does not exist in database
    ]
