# Generated by Django 5.0.4 on 2025-09-25 18:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in_at', models.DateTimeField()),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=32, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to='businesses.employee')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_records', to='hr.office')),
            ],
            options={
                'db_table': 'hr_time_records',
                'indexes': [models.Index(fields=['employee', 'check_in_at'], name='hr_time_rec_employe_056a2a_idx'), models.Index(fields=['employee', 'check_out_at'], name='hr_time_rec_employe_13972f_idx')],
            },
        ),
    ]
