# Generated by Django 5.2.6 on 2025-09-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0001_initial"),
    ]

    operations = []
