name: Frontend CI

on:
  push:
    branches:
      - dev
      - main
      - 'feature/**'
    paths:
      - 'business/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches:
      - dev
      - main
    paths:
      - 'business/**'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: business

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug files
        run: |
          pwd
          ls -la
          echo "Parent dir:" && ls -la ..

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            business/package-lock.json
            business/package.json

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            echo "Using npm ci (lockfile present)"
            npm ci
          else
            echo "No lockfile found, falling back to npm install"
            npm install
          fi

      - name: Build
        env:
          # Override khi cần trỏ API khác trong CI
          NUXT_PUBLIC_API_BASE: "http://localhost:8008/api/v1"
        run: npm run build

      - name: Upload Nuxt build artifact
        uses: actions/upload-artifact@v4
        with:
          name: business-nuxt-build-${{ github.sha }}
          path: |
            .nuxt/**
            .output/**
            .nuxt/dist/server/client.manifest.json
